openapi: 3.0.0
info:
  description: 'Secret key:`416c46727662229e0326014748346721` This is our RESTFUL API server. Members: Juancarlos Ramirez, Oscar Pena, Budelio Chavez'
  version: 1.0.0
  title: Web Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Say Hello
    description: Send a hello message to the server
  - name: Weather
    description: Get weather by zip code
paths:
  /hello:
    get:
      tags:
        - Say Hello
      summary: Say hello to the server
      description: Returns a message back saying hello
      responses:
        '200':
          description: successful operation
  '/weather/{zipcode}':
    get:
      tags:
        - Weather
      summary: Enter zip code and get the current weather
      description: Returns current weather from API
      operationId: get_weather_zipcode
      parameters:
        - name: zipcode
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - Authorization: []

servers:
  - url: http://127.0.0.1:5000/

components:
  securitySchemes:
    Authorization:
      description: '`416c46727662229e0326014748346721`'
      type: apiKey
      name: appid
      in: header
